[package]
name = "ZazaPotify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustube="0.6.0"
rodio = "0.17.1"
url = "2.2.2"
tokio = { version="1.11.0", features = ["rt-multi-thread", "time"] }
